### ISSUE TITLE
Errors on localhost

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/website#1040]
Both @alexandergimson and I are having an issue with making changes to the website and running them locally : 

```
:image_optim is deprecated. Please use `:imageoptim` instead.
== The Middleman is loading
== LiveReload is waiting for a browser to connect
== View your site at "http://localhost:4567", "http://127.0.0.1:4567"
== Inspect your site configuration at "http://localhost:4567/__middleman", "http://127.0.0.1:4567/__middleman"
E, [2017-10-31T17:31:48.085945 #91037] ERROR -- : exception while processing events: undefined local variable or method `ignore_manager' for #<Middleman::Application:0x70188132406220> Backtrace:
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/middleman-livereload-3.1.1/lib/middleman-livereload/extension_3_1.rb:35:in `block (2 levels) in initialize'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.2.1/lib/middleman-core/sources.rb:284:in `block (2 levels) in changed'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.2.1/lib/middleman-core/sources.rb:284:in `each'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.2.1/lib/middleman-core/sources.rb:284:in `block in changed'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.2.1/lib/middleman-core/sources.rb:368:in `call'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.2.1/lib/middleman-core/sources.rb:368:in `block in run_callbacks'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.2.1/lib/middleman-core/sources.rb:361:in `run_callbacks'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.2.1/lib/middleman-core/sources.rb:351:in `did_change'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `block in execute'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `execute'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.2.1/lib/middleman-core/sources/source_watcher.rb:288:in `update'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.2.1/lib/middleman-core/sources/source_watcher.rb:251:in `on_listener_change'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/listen-3.0.8/lib/listen/event/config.rb:23:in `call'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/listen-3.0.8/lib/listen/event/config.rb:23:in `call'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/listen-3.0.8/lib/listen/event/processor.rb:115:in `_process_changes'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/listen-3.0.8/lib/listen/event/processor.rb:19:in `block in loop_for'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/listen-3.0.8/lib/listen/event/processor.rb:15:in `loop'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/listen-3.0.8/lib/listen/event/processor.rb:15:in `loop_for'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/listen-3.0.8/lib/listen/event/loop.rb:84:in `_wait_for_changes'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/listen-3.0.8/lib/listen/event/loop.rb:42:in `block in setup'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/listen-3.0.8/lib/listen/internals/thread_pool.rb:6:in `call'
 -- /Users/nikesh/.rvm/gems/ruby-2.2.3/gems/listen-3.0.8/lib/listen/internals/thread_pool.rb:6:in `block in add'
```

**Comment by alexandergimson** [comment]
Running bundler version: 1.15.4.

**Comment by nikeshashar** [comment]
Found this link : https://github.com/middleman/middleman-livereload/issues/93

**Comment by nikeshashar** [comment]
Ran `gem update middleman-livereload` and got it to 

```
middleman-livereload (3.1.1)
      em-websocket (>= 0.2.0)
      middleman-core (>= 3.0.2)
      multi_json (~> 1.0)
      rack-livereload
```

**Comment by nikeshashar** [comment]
Made a change and it still comes up with the same error message.

**Comment by rachelcdavies** [comment]
I've started looking into this

**Comment by rachelcdavies** [comment]
I see the same warning messages but what's the problem it's causing? I can run the site locally just fine.

**Comment by rachelcdavies** [comment]
Here's what I did:
```
bundle install

Warning: the running version of Bundler (1.14.6) is older than the version that created the lockfile (1.15.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.

Using middleman-imageoptim 0.2.1 from https://github.com/plasticine/middleman-imageoptim (at master@a539cae)
Using middleman-livereload 3.1.1

Post-install message from image_optim:
Rails image assets optimization is extracted into image_optim_rails gem
You can safely remove `config.assets.image_optim = false` if you are not going to use that gem

middleman s
:image_optim is deprecated. Please use `:imageoptim` instead.

Loads site as normal.
```

**Comment by rachelcdavies** [comment]
I can also run fine with 1.15.3, don't want to upgrade to 1.15.4 due to an issue with Hub.
Adding Roi to this ticket so he can get rid of the warning message.

**Comment by roidriscoll** [comment]
regarding that error message: https://github.com/plasticine/middleman-imageoptim/issues/49
